version: '2'
services:
  ssm-config:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: npm run coverage
    environment:
      NODE_ENV: test
    volumes:
     - .:/home/app/src
     - /home/app/src/node_modules